config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  root 'home#index'
  get '/search', to: 'home#search', as: 'search'

  devise_for(:users,
             path: 'auth',
             skip: %i(registrations),
             controllers: {
                 sessions: 'auth/sessions',
                 omniauth_callbacks: 'auth/omniauth_callbacks'
             }
  )

  as :user do
    get 'auth/sign_up', to: 'auth/registrations#new', as: :new_user_registration
    post 'auth/sign_up', to: 'auth/registrations#new', as: :user_registration
  end

  resources :authors, only: %i(show index)
  resources :categories, only: :show

  resources :books, only: %i(show index) do
    resources :reviews, only: %i(new create index)
    resources :wishes, only: :create
  end

  resources :wishes, only: :destroy

  resources :users, only: :none do
    resources :wishes, only: :index
  end

  scope 'order' do
    post '/:class/:id', to: 'order#add_product', as: 'order_add_product'
    delete '/:class/:id', to: 'order#remove_product', as: 'order_remove_product'
  end

  resources :shopping_checkout, only: %i(show update)

  resource :shopping_cart, controller: :shopping_cart, path: '/', only: %i(show) do
    get 'complete'
  end

  namespace :settings do
    resource :billing_address, :shipping_address, except: %i(new edit)

    resource :profile, except: %i(new edit create) do
      put 'update_info'
      put 'update_password'
    end

    # query and index hmmm
    resource :history, only: :none do
      get 'in_queue'
      get 'in_delivery'
      get 'delivered'
      get 'canceled'
    end
  end

  # mount Shopping::Engine => '/cart', as: 'shopping'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/wish.rb
class Wish
  belongs_to :user
  belongs_to :book

  validates :user, :book, presence: true
  validates_uniqueness_of :user_id, scope: :book_id
end

app/views/wishes/index.html.haml
- title t('wishes.name')

%h1.page-header= t('wishes.name')

- if @user.wishes.empty?
  .wishes-for
    = (current_user.id == @user.id) ? t('wishes.my_empty') : t('wishes.user_empty', user: @user)
- else
  .wishes-for
    = (current_user.id == @user.id) ? t('wishes.my_wishes') : t('wishes.user_wishes', user: @user)

  %ul.list-unstyled.wishes-list
    - @user.wishes.each do |w|
      %li
        = link_to w.book, w.book
        - if can?(:destroy, w)
          = form_tag wish_path(w), method: :delete do
            = button_tag t('wishes.remove'), name: nil, class: 'btn btn-warning'