config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  root 'home#index'
  get '/search', to: 'home#search', as: 'search'

  devise_for(:users,
             path: 'auth',
             skip: %i(registrations),
             controllers: {
                 sessions: 'auth/sessions',
                 omniauth_callbacks: 'auth/omniauth_callbacks'
             }
  )

  as :user do
    get 'auth/sign_up', to: 'auth/registrations#new', as: :new_user_registration
    post 'auth/sign_up', to: 'auth/registrations#new', as: :user_registration
  end

  resources :authors, only: %i(show index)
  resources :categories, only: :show

  resources :books, only: %i(show index) do
    resources :reviews, only: %i(new create index)
    resources :wishes, only: :create
  end

  resources :wishes, only: :destroy

  resources :users, only: :none do
    resources :wishes, only: :index
  end

  scope 'order' do
    post '/:class/:id', to: 'order#add_product', as: 'order_add_product'
    delete '/:class/:id', to: 'order#remove_product', as: 'order_remove_product'
  end

  resources :shopping_checkout, only: %i(show update)

  resource :shopping_cart, controller: :shopping_cart, path: '/', only: %i(show) do
    get 'complete'
  end

  namespace :settings do
    resource :billing_address, :shipping_address, except: %i(new edit)

    resource :profile, except: %i(new edit create) do
      put 'update_info'
      put 'update_password'
    end

    # query and index hmmm
    resource :history, only: :none do
      get 'in_queue'
      get 'in_delivery'
      get 'delivered'
      get 'canceled'
    end
  end

  # mount Shopping::Engine => '/cart', as: 'shopping'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @best_sellers = Book.best_sellers.to_a
  end

  def search
    @query = params[:query]
    @search_by = params[:search_by]
    @results = Search.new(@query, @search_by).search.results
  end
end

app/views/home/index.html.haml
- if @best_sellers && @best_sellers.empty?
  %h3= t('home.no_popular')
- else
  .carousel#best-sellers-carousel.slide{'data-ride': 'carousel'}
    .carousel-inner{'role': 'listbox'}
      - @best_sellers.each_with_index do |item, index|
        .item{class: (index == 0 ? 'active' : '')}
          %img{'src': item.cover.url}
          .title.slide-info #{item}
          .author.slide-info by #{item.author}

          - if item.short_description
            .short-description.slide-info= item.short_description

          = link_to glyph_icon(:eye_open) + ' View more info', book_path(item),  {class: 'btn btn-default more-info'}

    %a.left.carousel-control{href: '#best-sellers-carousel', role: 'button', 'data-slide': 'prev'}
      = glyph_icon(:chevron_left)

    %a.right.carousel-control{href: '#best-sellers-carousel', role: 'button', 'data-slide': 'next'}
      = glyph_icon(:chevron_right)

app/views/home/search.html.haml
- title t('search.title')

= form_tag(search_path, {method: :get, class: 'form-inline search'}) do
  .form-group
    = text_field_tag :query, @query, placeholder: t('search.placeholder'), class: 'form-control'
  .radio
    %label
      = radio_button_tag :search_by, 'books', @search_by.nil? || @search_by == 'books'
      = t('search.by_books')
  .radio
    %label
      = radio_button_tag :search_by, 'authors', @search_by == 'authors'
      = t('search.by_authors')
  = button_tag t('search.name'), class: 'btn btn-primary btn', name: nil

- if @query.present? && @search_by.present?
  - if @results.empty?
    .search-results-query
      = t('search.no_result')
      %strong
        = @query
  - else
    .search-results-query
      = t('search.results_for')
      %strong
        = @query
    %ol.search-results-list
      - @results.each do |r|
        %li
          = link_to r, r, target: '_blank'