config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  root 'home#index'
  get '/search', to: 'home#search', as: 'search'

  devise_for(:users,
             path: 'auth',
             skip: %i(registrations),
             controllers: {
                 sessions: 'auth/sessions',
                 omniauth_callbacks: 'auth/omniauth_callbacks'
             }
  )

  as :user do
    get 'auth/sign_up', to: 'auth/registrations#new', as: :new_user_registration
    post 'auth/sign_up', to: 'auth/registrations#new', as: :user_registration
  end

  resources :authors, only: %i(show index)
  resources :categories, only: :show

  resources :books, only: %i(show index) do
    resources :reviews, only: %i(new create index)
    resources :wishes, only: :create
  end

  resources :wishes, only: :destroy

  resources :users, only: :none do
    resources :wishes, only: :index
  end

  scope 'order' do
    post '/:class/:id', to: 'order#add_product', as: 'order_add_product'
    delete '/:class/:id', to: 'order#remove_product', as: 'order_remove_product'
  end

  resources :shopping_checkout, only: %i(show update)

  resource :shopping_cart, controller: :shopping_cart, path: '/', only: %i(show) do
    get 'complete'
  end

  namespace :settings do
    resource :billing_address, :shipping_address, except: %i(new edit)

    resource :profile, except: %i(new edit create) do
      put 'update_info'
      put 'update_password'
    end

    # query and index hmmm
    resource :history, only: :none do
      get 'in_queue'
      get 'in_delivery'
      get 'delivered'
      get 'canceled'
    end
  end

  # mount Shopping::Engine => '/cart', as: 'shopping'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/views/reviews/index.html.haml
- title t('review.reviews_for', name: @book)

%h1= t('review.reviews_for', name: @book)

.reviews
  .add_new
    - if current_user
      - if current_user.is_left_review?(@book)
        = t 'review.review_left'
      - else
        = link_to t('review.add_new'), new_book_review_path(@book)
    - else
      = t 'review.not_singed_in'
      = link_to t('auth.sign_in'), new_session_path(resource_name)

  %ul.reviews-list.list-unstyled
    - @reviews.each do |review|
      %li.review
        .r
          - review.rating.times do
            = glyph_icon(:star)
        .by
          = t 'review.left_by', name: review.user
        .note
          = review.note

  %div= paginate @reviews
  %div= page_entries_info @reviews

app/views/reviews/new.html.haml
- title t('review.review_for', name: @book)

%h1= t('review.review_for', name: @book)

= render partial: '/helpers/validation_errors', locals: { suspect: @review }
= form_for @review, url: book_reviews_path(@book) do |f|
  .form-group
    = f.label :rating
    = f.select :rating, Review::RATING, {}, class: 'form-control'
  .form-group
    = f.label :note
    = f.text_area :note, class: 'form-control'
  = f.submit t('review.add_new'), class: 'btn btn-primary'