config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  root 'home#index'
  get '/search', to: 'home#search', as: 'search'

  devise_for(:users,
             path: 'auth',
             skip: %i(registrations),
             controllers: {
                 sessions: 'auth/sessions',
                 omniauth_callbacks: 'auth/omniauth_callbacks'
             }
  )

  as :user do
    get 'auth/sign_up', to: 'auth/registrations#new', as: :new_user_registration
    post 'auth/sign_up', to: 'auth/registrations#new', as: :user_registration
  end

  resources :authors, only: %i(show index)
  resources :categories, only: :show

  resources :books, only: %i(show index) do
    resources :reviews, only: %i(new create index)
    resources :wishes, only: :create
  end

  resources :wishes, only: :destroy

  resources :users, only: :none do
    resources :wishes, only: :index
  end

  scope 'order' do
    post '/:class/:id', to: 'order#add_product', as: 'order_add_product'
    delete '/:class/:id', to: 'order#remove_product', as: 'order_remove_product'
  end

  resources :shopping_checkout, only: %i(show update)

  resource :shopping_cart, controller: :shopping_cart, path: '/', only: %i(show) do
    get 'complete'
  end

  namespace :settings do
    resource :billing_address, :shipping_address, except: %i(new edit)

    resource :profile, except: %i(new edit create) do
      put 'update_info'
      put 'update_password'
    end

    # query and index hmmm
    resource :history, only: :none do
      get 'in_queue'
      get 'in_delivery'
      get 'delivered'
      get 'canceled'
    end
  end

  # mount Shopping::Engine => '/cart', as: 'shopping'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/views/settings/profiles/show.html.haml
- title t('settings')

= render layout: 'layouts/settings' do

  %h2= t('profile.name')

  %h3= t('profile.info_name')

  - if current_p? update_info_settings_profile_path
    = render partial: '/helpers/validation_errors', locals: { suspect: @user }

  = form_for @user, method: :put, url: update_info_settings_profile_path, html: { class: 'update-user-info' } do |f|
    .form-group
      = f.label :first_name
      = f.text_field :first_name, autofocus: true, class: 'form-control'
    .form-group
      = f.label :last_name
      = f.text_field :last_name, class: 'form-control'
    .form-group
      = f.label :email
      = f.email_field :email, class: 'form-control'
    = f.button t('save'), class: 'btn btn-primary'


  %h3= t('profile.password_name')

  - if current_p? update_password_settings_profile_path
    = render partial: '/helpers/validation_errors', locals: { suspect: @user }

  = form_for @user, method: :put, url: update_password_settings_profile_path, html: { class: 'update-user-pass' } do |f|
    .form-group
      = f.label :current_password
      = f.password_field :current_password, class: 'form-control', autocomplete: 'off'
    .form-group
      = f.label :password
      = f.password_field :password, class: 'form-control', autocomplete: 'off'
    .form-group
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: 'form-control', autocomplete: 'off'
    = f.button t('save'), class: 'btn btn-primary'

  %h3= t('profile.destroy_name')
  = form_tag(settings_profile_path, {method: :delete, class: 'delete-account'}) do
    .checkbox
      %label
        = check_box_tag :want_to_delete, nil
        = t('profile.destroy_confirm')
    = button_tag t('destroy'), class: 'btn btn-danger'